### ISSUE TITLE
Will  the app get rejected if i you this library?

### ISSUE THREAD

**Issue by joemat04** [envoy/Embassy#28]
i didn't found any discussion thread here, that's why i posted it has an issue.

Will apple allow to create http server in app, Is there any chances of getting rejection due to this?

Regards 
Joe

**Comment by fangpenlin** [comment]
Hi Joe,

We are not Apple, and we don't use it for anything else other than UI automatic testing, there is no way we can tell will Apple reject your app or not. However, what this library does is pretty simple, it runs an HTTP server. So I think the right question to ask would be

> Will Apple reject my app if I run an HTTP server in my app?

And according to what I have seen in App Store, for example, I know there is [AcePlayer](https://itunes.apple.com/us/app/aceplayer-for-mkv-avi-rmvb-flac-ape-and-so-on/id480881925?mt=8) runs an HTTP server in the app, so that you can visit the page served by the app and upload your video file. So my guess is, it should be okay. Nevertheless, I would suggest you read [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/) carefully see if there is any explicit prohibition on running a server in your app.

Hope this could help.
