### ISSUE TITLE
Static resources?

### ISSUE THREAD

**Issue by kuyawa** [envoy/Embassy#33]
Hey guys, love this project, been playing with it for a couple of days from the simplest scenario adding little things like templates (Stencil) and databases (Postgres) and it's looking damn good.

This is what I got so far trying to simplify the entry point of an Ambassador app tweaking a little bit of code in a Server.swift file:

```swift
// MAIN

let router = Router()

//router["/"]     = App.index()  // here
router["/index"]  = App.index()
router["/users"]  = App.users()
router["/delay"]  = App.delay()
router["/test"]   = App.test()
router["/static"] = App.staticResource() // here
router["/404"]    = App.notFound()
router.notFound   = App.notFound()

let server = Server()
server.run(router)
```

Ok, two things: 

1. How to serve static resources? I couldn't find any info in the very scarce docs. Is there any manual/doc anywhere else?

2. As you can see, the root is commented since uncommenting it would cause all paths to be redirected to the root, perhaps due to the regex evaluation? So, how do you route the root like localhost:8080/ as "/"?

Thanks for all the cool stuff, this project rocks!

**Comment by fangpenlin** [comment]
@kuyawa 

For 1., there is no build-in things for static resource, the easiest way to do it is probably using `DataResponse` from Ambassador

https://github.com/envoy/Ambassador#dataresponse

Like this

```Swift
router["/foo.png"] = DataResponse(
    statusCode: 200,
    contentType: "image/png"
) { environ -> Data in
    return try! Data(contentsOf: URL(fileURLWithPath: "/path/to/image.png"))
}
```

for the second question, as the `Router` is matching as simple regular expression, which means it will try to match whatever possible comes first. If you put `/` up front, surely it will match everything starts with `/`. To do a complete match, you can modify the `/` to be

```
/$
```

instead. Which means it will also match the end of string, as a result, only exact `/` will be match instead of prefixes.

If you don't like the way router works, I would suggest write your own router, as it's super simple to build one, here's the source code of build-in router from Ambassador

https://github.com/envoy/Ambassador/blob/master/Ambassador/Router.swift

**Comment by kuyawa** [comment]
Oh beautiful! Thanks, that was super easy. I love Embassy/Ambassador :)
